version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - importas
    - ineffassign
    - lll
    - modernize
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    modernize:
      disable:
        - omitzero
    importas:
      alias:
        - pkg: sigs.k8s.io/controller-runtime/pkg/log
          alias: logf
        - pkg: sigs.k8s.io/cluster-api/api/core/v1beta2
          alias: clusterv1
        - pkg: github.com/scaleway/cluster-api-provider-scaleway/api/v1alpha2
          alias: infrav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: utilerrors
        - pkg: github.com/scaleway/cluster-api-provider-scaleway/internal/service/scaleway/lb/util
          alias: lbutil
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - lll
        path: cmd/main.go
      - linters:
          - lll
        path: test/e2e/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - staticcheck
        text: "ST1005"
      - linters:
          - staticcheck
        text: "QF1008"
      - linters:
          - staticcheck
        text: "ST1001"
        path: test/e2e/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - blank
        - dot
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: strict
    paths:
      - zz_generated.*\.go$
      - third_party$
      - builtin$
      - examples$
