// Code generated by MockGen. DO NOT EDIT.
// Source: ../ipam.go
//
// Generated by this command:
//
//	mockgen -destination ipam_mock.go -package mock_client -source ../ipam.go -typed
//

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	reflect "reflect"

	ipam "github.com/scaleway/scaleway-sdk-go/api/ipam/v1"
	scw "github.com/scaleway/scaleway-sdk-go/scw"
	gomock "go.uber.org/mock/gomock"
)

// MockIPAMAPI is a mock of IPAMAPI interface.
type MockIPAMAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIPAMAPIMockRecorder
	isgomock struct{}
}

// MockIPAMAPIMockRecorder is the mock recorder for MockIPAMAPI.
type MockIPAMAPIMockRecorder struct {
	mock *MockIPAMAPI
}

// NewMockIPAMAPI creates a new mock instance.
func NewMockIPAMAPI(ctrl *gomock.Controller) *MockIPAMAPI {
	mock := &MockIPAMAPI{ctrl: ctrl}
	mock.recorder = &MockIPAMAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPAMAPI) EXPECT() *MockIPAMAPIMockRecorder {
	return m.recorder
}

// ListIPs mocks base method.
func (m *MockIPAMAPI) ListIPs(req *ipam.ListIPsRequest, opts ...scw.RequestOption) (*ipam.ListIPsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListIPs", varargs...)
	ret0, _ := ret[0].(*ipam.ListIPsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIPs indicates an expected call of ListIPs.
func (mr *MockIPAMAPIMockRecorder) ListIPs(req any, opts ...any) *MockIPAMAPIListIPsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{req}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIPs", reflect.TypeOf((*MockIPAMAPI)(nil).ListIPs), varargs...)
	return &MockIPAMAPIListIPsCall{Call: call}
}

// MockIPAMAPIListIPsCall wrap *gomock.Call
type MockIPAMAPIListIPsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPAMAPIListIPsCall) Return(arg0 *ipam.ListIPsResponse, arg1 error) *MockIPAMAPIListIPsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPAMAPIListIPsCall) Do(f func(*ipam.ListIPsRequest, ...scw.RequestOption) (*ipam.ListIPsResponse, error)) *MockIPAMAPIListIPsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPAMAPIListIPsCall) DoAndReturn(f func(*ipam.ListIPsRequest, ...scw.RequestOption) (*ipam.ListIPsResponse, error)) *MockIPAMAPIListIPsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockIPAM is a mock of IPAM interface.
type MockIPAM struct {
	ctrl     *gomock.Controller
	recorder *MockIPAMMockRecorder
	isgomock struct{}
}

// MockIPAMMockRecorder is the mock recorder for MockIPAM.
type MockIPAMMockRecorder struct {
	mock *MockIPAM
}

// NewMockIPAM creates a new mock instance.
func NewMockIPAM(ctrl *gomock.Controller) *MockIPAM {
	mock := &MockIPAM{ctrl: ctrl}
	mock.recorder = &MockIPAMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPAM) EXPECT() *MockIPAMMockRecorder {
	return m.recorder
}

// FindPrivateNICIPs mocks base method.
func (m *MockIPAM) FindPrivateNICIPs(ctx context.Context, privateNICID string) ([]*ipam.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrivateNICIPs", ctx, privateNICID)
	ret0, _ := ret[0].([]*ipam.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrivateNICIPs indicates an expected call of FindPrivateNICIPs.
func (mr *MockIPAMMockRecorder) FindPrivateNICIPs(ctx, privateNICID any) *MockIPAMFindPrivateNICIPsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrivateNICIPs", reflect.TypeOf((*MockIPAM)(nil).FindPrivateNICIPs), ctx, privateNICID)
	return &MockIPAMFindPrivateNICIPsCall{Call: call}
}

// MockIPAMFindPrivateNICIPsCall wrap *gomock.Call
type MockIPAMFindPrivateNICIPsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPAMFindPrivateNICIPsCall) Return(arg0 []*ipam.IP, arg1 error) *MockIPAMFindPrivateNICIPsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPAMFindPrivateNICIPsCall) Do(f func(context.Context, string) ([]*ipam.IP, error)) *MockIPAMFindPrivateNICIPsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPAMFindPrivateNICIPsCall) DoAndReturn(f func(context.Context, string) ([]*ipam.IP, error)) *MockIPAMFindPrivateNICIPsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
